
name: Deploy to Vercel

on:
  push:
    branches:
    - main
    - release/*

jobs:
  build_website_files:
    name: Build Files
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Install Vercel
        run: npm install vercel
          
      - name: Install depends
        run: npm ci
        
      - name: Build site
        run: npm run build-prod

      - name: Deploy App
        run: npx vercel deploy --cwd ./dist --prebuilt --token ${{ secrets.VECELKEY }}
