
name: Deploy to Vercel

on:
  push:
    branches:
    - main
    - release/*

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  build_website_files:
    name: Build Files
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Install Vercel
        run: npm install vercel
          
      - name: Install depends
        run: npm ci
        
      - name: Build site
        run: npm run build-prod

      - name: Get latest vercel config
        run: npx vercel pull --token ${{ secrets.VECELKEY }}

      - name: Build a vercel project
        run: npx vercel build --token ${{ secrets.VECELKEY }}

      - name: Deploy App
        run: npx vercel --prebuilt --token ${{ secrets.VECELKEY }}
